spring:
  profiles: development,dev,default
  
system:
  cas:
    serverUrl: 'https://logint.pousheng.com'
    loginUrl: '${system.cas.serverUrl}/login'
    logoutUrl: '${system.cas.serverUrl}/logout'
    cookieSessionId: yysportsCasSid   
    restServer: 'http://10.0.0.168:9003/yysports-cas-service'
    cookieDomain: manager.yy-sports.com
    cookiePath: /
    expiredTime: 1800

---

spring: 
  profiles: production,prod

system:
  cas:
    serverUrl: 'https://logint.pousheng.com1'
    loginUrl: '${system.cas.serverUrl}/login1'
    logoutUrl: '${system.cas.serverUrl}/logout1'
    cookieSessionId: yysportsCasSidProd    
    restServer: 'http://10.0.0.168:9003/yysports-cas-service'
    cookieDomain: manager.yy-sports.com
    cookiePath: /
    expiredTime: 1800